version: "3.7"

services:

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"

  langitstars:
    build: ./app
    container_name: langitstars
    restart: always
    environment:
      - APP_NAME=langitstars
    expose:
      - 8080
